version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3336:3336'
    environment:
       MYSQL_DATABASE: 'chatroom'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '123456'
       MYSQL_ROOT_PASSWORD: '123456'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/chatroom
    ports:
      - "8000:8000"
    depends_on:
      - db